name: code_builder_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  lints: ^5.0.0
  test: ^1.24.0
